### PR TITLE
Fix tests in CI

### LINKED ISSUE #348: Fix CI
Tests have not been running in CI since [Wallaby was added](https://github.com/pulibrary/dpul-collections/commit/8fc3fe96613d188ee1367e59e4852406e80343d6#diff-dfa6f4ed74c90e5d4fda283d547d366586e690387289bcfd473e3fa5f9ace308R97).

### PR DESCRIPTION
**Pull request by eliotjordan**
Closes #348

### CODE REVIEW

File: test/dpul_collections_web/live/browse_live_test.exs [hunk 1]
```diff
@@ -80,4 +80,33 @@ defmodule DpulCollectionsWeb.BrowseLiveTest do
     view
     |> has_element?(".item-link")
   end
+
+  test "renders primary thumbnail only  when there is only one image url", %{conn: conn} do
```
Comment (hackartisan) [inline test/dpul_collections_web/live/browse_live_test.exs:84]: Should this new test be added here, or maybe in a different PR?

**Review by hackartisan — CHANGES_REQUESTED** [review]

File: test/dpul_collections_web/live/browse_live_test.exs (hunk 1 above)
Comment (tpendragon) [reply test/dpul_collections_web/live/browse_live_test.exs:84]: If it's not here this PR fails because of coverage.

**Comment by tpendragon** [comment]
Created https://github.com/pulibrary/dpul-collections/issues/352

File: test/dpul_collections_web/live/browse_live_test.exs (hunk 1 above)
Comment (hackartisan) [reply test/dpul_collections_web/live/browse_live_test.exs:84]: aha, thanks

**Review by hackartisan — APPROVED** [review]
